# Rapport sur la voie lactée et la matière noire 

## Compréhension du sujet :

Pour bien situer le sujet il est nécessaire de comprendre ce qu'est la radiosastronomie et les coordonnées galactiques ainsi que la spectroscopie de l'hydrogène neutre.

La spectroscopie est une méthode essentielle à l'astrophysique pour mieux connaître les objets célestes de notre galaxie. Il s'agit d'étudier le spectre d'un phénomène ou d'un objet physique afin d'en déterminer les caractéristiques (composition, température, distance). 
L'hydrogène étant le constituant principal de l'univers et donc du milieu interstellaire des galaxies, l'étude de son spectre apporte de préciseuses informations sur les objets présents dans la voie Lactée. 


- Qu'est ce que la matière noire ?
- Où se trouve la prinicpale masse dans la Voie lactée?
- Comment expliquer les différences entre les vitesses orbitales théoriques et les vitesses orbitales observées?


    

### Fonction qui calcule la vitesse du nuage de gaz et la distance au centre galactique:


In [ ]:
from pylab import *
import numpy as np

def vitessegaz(longitude, vitesserad):
    
    #vitesse du Soleil autour du centre galactique en (km/s)
    v0=220
    #Distance entre le soleil et le centre galactique(kpc, 1 pc=3.09*10**6m)
    R0=8.5
  
    #vitesses orbitales
    V=0
    #Distance entre le nuage et le centre galactique
    R=0
    
    V=vitesserad+v0*sin(math.radians(longitude))
    R=R0*sin(math.radians(longitude))
    
    
    return (R, V)

print(vitessegaz(0,130))
print('longitude 1')
print(vitessegaz(1,200))
print(vitessegaz(2,252))
print('longitude 3')
print(vitessegaz(3,229))
print(vitessegaz(4,175))
print(vitessegaz(5,182))
print("longitude 6")
print(vitessegaz(6,185))
print(vitessegaz(7,185))
print(vitessegaz(8,182))
print("longitude 10:")
print(vitessegaz(10,175))
print(vitessegaz(12,146))
print(vitessegaz(15,140))
print(vitessegaz(17,132))
print("longitude 20")
print(vitessegaz(20,120))
print(vitessegaz(21,120))
print(vitessegaz(24,101))
print(vitessegaz(25,99))
print(vitessegaz(27,97))
print(vitessegaz(32,99))
print(vitessegaz(35,86))
print(vitessegaz(38,80))
print('longitude 40')
print(vitessegaz(40,65))
print(vitessegaz(45,60))
print(vitessegaz(47,58))
print(vitessegaz(50,49))
print(vitessegaz(55,41))
print('longitude 60')
print(vitessegaz(60,28))
print(vitessegaz(62,23))
print(vitessegaz(65,18))
print(vitessegaz(67,8))
print ('longitude 70')
print(vitessegaz(70,6))
print(vitessegaz(72,3))
print(vitessegaz(75,0))



In [16]:
import numpy as np
Vr,T=np.loadtxt('spectre.txt',usecols=(0,1),unpack=True)
Vr,T

(array([ -55.,  -32.,  -16.,    2.,   26.,   34.,   44.,   57.,   70.,
          78.,   89.,   93.,  107.,  130.]),
 array([   1.63,   36.84,   57.17,   52.6 ,   96.68,   78.13,   96.46,
          77.17,   86.4 ,   92.65,   96.75,  101.45,   92.73,    1.18]))

In [ ]:
figure(figsize=(12,6), dpi=80)
plot(Vr, T, 'bo-')
plt.title("Spectre Température en fonction de la vitesse radiale, à la longitude 30")
plt.xlabel('Vitesse radiale(km.s^-1)')
plt.ylabel('Température ')
show()


In [ ]:
import numpy as np
V,R=np.loadtxt('courberotation.txt',skiprows=1,usecols=(1,2),unpack=True)
V,R

In [7]:
figure(figsize=(12,6), dpi=80)
plot(V, R,"ro")
plt.title("Courbe de rotation de la Voie lactée")
plt.xlabel('Distance au centre galactique(kpc)')
plt.ylabel('Vitesse orbitale du nuage de gaz (km/s)')
show()


D'après la deuxième loi de Newton, on peut déduire des valeurs théoriques des vitesses orbitales des nuages de gaz. Effectivement, sous l'effet de la force gravitationnelle dont l'intensité décroit avec la distance entre les deux objets étudiés, on peut supposer que lorsque l'on s'éloigne du centre galactique, cette force diminue et donc la vitesse décroît. Or en réalité, la théorie n'est pas vérifiée comme le montre la courbe de rotation ci dessus, la vitesse orbitale des nuage de gaz augmente lorsque le rayon augmente avant de se stabiliser lorsque le rayson approche les 1kpc soit 3,086*10^19m du centre galactique. Nous allons tenter de modéliser ces observations sur les vitesses orbitales avec des simulations.

### Simuler la vitesse la vitesse orbitale en fonction de l'éloignement du centre galactique

In [31]:
#Animation vitesse/distance centre galactique

import numpy as np
from matplotlib import pyplot as plt
from matplotlib import animation
import matplotlib.pyplot as plt
from __future__ import division 
from scipy import *                  
from pylab import * 
import os

def cercle(R,pas):
    angle=0
    avancement=pas
    while angle<2*np.pi:
        angle=angle+avancement
        x=R*cos(angle)
        y=R*sin(angle)
        plt.axis([-100,100,-100,100])
        plot(x,y,'co')
        
plt.axis("equal")
plt.show()

fig = plt.figure()
fig.set_dpi(100)
fig.set_size_inches(7, 6.5)

ax = plt.axes(xlim=(-10, 10), ylim=(-10, 10))

size = 1
xcenter = 0
ycenter = 0
radius = 1

patch = plt.Circle((0,0), size, fc='b')

def init():
    ax.add_patch(patch)
    return patch,

def animate(t):
    x, y = patch.center
    x = xcenter + 20* np.sin(t*np.pi/4)
    y = ycenter + 20 * np.cos(t*np.pi/4)
    patch.center = (x, y)
    return patch,


def animate2(t):
    x, y = patch.center
    x = xcenter + 40 * np.sin(t*np.pi/8)
    y = ycenter + 40 * np.cos(t*np.pi/8)
    patch.center = (x, y)
    return patch,

def animate3(t):
    x, y = patch.center
    x = xcenter + 60 * np.sin(t*np.pi/16)
    y = ycenter + 60 * np.cos(t*np.pi/16)
    patch.center = (x, y)
    return patch,

def animate4(t):
    x, y = patch.center
    x = xcenter + 80 * np.sin(t*np.pi/24)
    y = ycenter + 80 * np.cos(t*np.pi/24)
    patch.center = (x, y)
    return patch,

anim = animation.FuncAnimation(fig, animate, 
                               init_func=init, 
                               frames=360, 
                               interval=20,
                               blit=True)

anim = animation.FuncAnimation(fig, animate2, 
                               init_func=init, 
                               frames=360, 
                               interval=20,
                               blit=True)

anim = animation.FuncAnimation(fig, animate3, 
                               init_func=init, 
                               frames=360, 
                               interval=20,
                               blit=True)

anim = animation.FuncAnimation(fig, animate4, 
                               init_func=init, 
                               frames=360, 
                               interval=20,
                               blit=True)

plt.axis("equal")
plt.plot(cercle(20,np.pi/4),cercle(40,np.pi/8), cercle(60,np.pi/16), cercle(80, np.pi/24))
plt.show()

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1487, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 535, in callit
    self.deletecommand(name)
  File "C:\Python34\lib\tkinter\__init__.py", line 394, in deletecommand
    self._tclCommands.remove(name)
AttributeError: 'NoneType' object has no attribute 'remove'


AttributeError: 'NoneType' object has no attribute 'tk'

In [26]:
def listex(angle, rayon):
    L=[]
    x=0
    for t in range(20):
        x=rayon*cos(t*angle)
        L.append(x)
    return L
        
def listey(angle, rayon):
    L=[]
    y=0
    for t in range(20):
        y=rayon*sin(t*angle)
        L.append(y)
    return L

In [27]:
listex(np.pi/4,20)

[20.0,
 14.142135623730951,
 1.2246467991473533e-15,
 -14.142135623730949,
 -20.0,
 -14.142135623730955,
 -3.6739403974420592e-15,
 14.142135623730947,
 20.0,
 14.142135623730955,
 6.1232339957367661e-15,
 -14.142135623730933,
 -20.0,
 -14.142135623730942,
 -8.572527594031473e-15,
 14.142135623730931,
 20.0,
 14.142135623730944,
 1.1021821192326179e-14,
 -14.14213562373093]

In [13]:
listey(np.pi/4,20)

[0.0,
 14.142135623730949,
 20.0,
 14.142135623730951,
 2.4492935982947065e-15,
 -14.142135623730949,
 -20.0,
 -14.142135623730955,
 -4.898587196589413e-15,
 14.142135623730947,
 20.0,
 14.142135623730967,
 7.3478807948841184e-15,
 -14.142135623730958,
 -20.0,
 -14.142135623730969,
 -9.7971743931788261e-15,
 14.142135623730956,
 20.0,
 14.142135623730972]

In [14]:
listex(np.pi/8,40)

[40.0,
 36.955181300451471,
 28.284271247461902,
 15.307337294603593,
 2.4492935982947065e-15,
 -15.307337294603588,
 -28.284271247461898,
 -36.955181300451471,
 -40.0,
 -36.955181300451471,
 -28.284271247461909,
 -15.307337294603613,
 -7.3478807948841184e-15,
 15.307337294603601,
 28.284271247461895,
 36.955181300451457,
 40.0,
 36.955181300451471,
 28.284271247461909,
 15.307337294603618]

In [15]:
listey(np.pi/8,40)

[0.0,
 15.307337294603592,
 28.284271247461898,
 36.955181300451471,
 40.0,
 36.955181300451471,
 28.284271247461902,
 15.307337294603595,
 4.898587196589413e-15,
 -15.307337294603586,
 -28.284271247461898,
 -36.955181300451457,
 -40.0,
 -36.955181300451464,
 -28.284271247461909,
 -15.307337294603617,
 -9.7971743931788261e-15,
 15.307337294603599,
 28.284271247461895,
 36.955181300451457]

In [23]:
import numpy as np
x1,y1=np.loadtxt('x1.txt',skiprows=1,usecols=(0,1),unpack=True)
x1,y1



(array([  2.00000000e+01,   1.40000000e+01,   1.00000000e-15,
         -1.40000000e+01,  -2.00000000e+01]),
 array([  0.00000000e+00,   1.40000000e+01,   2.00000000e+01,
          1.40000000e+01,   2.00000000e-15]))

In [24]:
import numpy as np
x2,y2=np.loadtxt('x2.txt',skiprows=1,usecols=(0,1),unpack=True)
x2,y2


(array([  4.00000000e+01,   3.60000000e+01,   2.80000000e+01,
          1.50000000e+01,   2.00000000e-15]),
 array([  0.,  15.,  28.,  36.,  40.]))

In [30]:
def xtemps(t):
    x=20*cos(t*np.pi/4)
    return x

def ytemps(t):
    y=20*cos(t*np.pi/4)
    return y

for t in range(0,20):
   print( xtemps(t),ytemps(t))

20.0 20.0
14.1421356237 14.1421356237
1.22464679915e-15 1.22464679915e-15
-14.1421356237 -14.1421356237
-20.0 -20.0
-14.1421356237 -14.1421356237
-3.67394039744e-15 -3.67394039744e-15
14.1421356237 14.1421356237
20.0 20.0
14.1421356237 14.1421356237
6.12323399574e-15 6.12323399574e-15
-14.1421356237 -14.1421356237
-20.0 -20.0
-14.1421356237 -14.1421356237
-8.57252759403e-15 -8.57252759403e-15
14.1421356237 14.1421356237
20.0 20.0
14.1421356237 14.1421356237
1.10218211923e-14 1.10218211923e-14
-14.1421356237 -14.1421356237
